# This workflow will install Python dependencies, run tests and lint with a single version of Python
# GitHub docs: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# uv docs: https://docs.astral.sh/uv/guides/integration/github/

name: Testing

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # Common platforms: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["ubuntu-latest"]
        # uv supports python 3.8 and higher
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout (official GitHub action)
      uses: actions/checkout@v4
      with:
        # Important for versioning plugins:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        # Install a specific version of uv.
        version: "0.7.3"
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Set up Python (using uv)
      run: |
        uv python install

    - name: Install the project
      run: |
        uv sync --all-extras --dev

    - name: Run linting
      run: |
        uv run codespell ./src
        uv run ruff check --output-format=github ./src
        uv run ruff format --check ./src

    - name: Test with example.csv
      run: |
        uv run schwab2pp example.csv -p test.csv
        diff example_out.csv test.csv
